#!/bin/bash

echo "========================================="
echo "     Winksy.ai GitHub Push Helper       "
echo "========================================="
echo ""
echo "This script will help you push to GitHub."
echo ""
echo "📝 INSTRUCTIONS:"
echo "1. First, create a GitHub Personal Access Token:"
echo "   - Go to: https://github.com/settings/tokens"
echo "   - Click 'Generate new token (classic)'"
echo "   - Give it a name like 'winksy-deploy'"
echo "   - Select scopes: 'repo' (full control)"
echo "   - Generate and copy the token"
echo ""
echo "2. When prompted for:"
echo "   - Username: Enter your GitHub username"
echo "   - Password: Paste your Personal Access Token (not your GitHub password)"
echo ""
echo "========================================="
echo ""
read -p "Press Enter when you have your token ready..."
echo ""
echo "Pushing to GitHub..."
echo ""

# Push to GitHub
git push origin main

echo ""
echo "✅ If successful, your code is now on GitHub!"
echo ""
echo "🚀 NEXT STEPS:"
echo "1. Go to https://vercel.com"
echo "2. Import your repository: flippingfelon/winksy.ai"
echo "3. Add environment variables from .env.local"
echo "4. Deploy!"
echo ""
echo "See DEPLOYMENT_GUIDE.md for detailed instructions."
